print('3개의 정수를 입력받아서 가장 큰 수와 가장 작은 수를 구하는 프로그램')
n1 = input('첫번째 정수 입력>>')
n2 = input('두번째 정수 입력>>')
n3 = input('세번째 정수 입력>>')
print('--------입력 결과--------')
print('가장 큰 수는 {}입니다.'.format(max(n1,max(n2,n3))))
print('가장 작은 수는 {}입니다.'.format(min(n1,min(n2,n3))))