A = "{:d}".format(52)
print()
B = "{:5d}".format(52)
C = "{:10d}".format(52)
print()
D =  "{:05d}".format(52)
E = "{:010d}".format(52)
F = "{:05d}".format(-52)
print()
print('기본')
print(A)
print("특정칸에 출력하기")
print(B)
print(C)
print("빈칸을 0으로 체우기")
print(D)
print(E)
print(F)